baseURL = 'https://example.com'
languageCode = 'zh-CN'
title = 'Title'
theme = "efimero"

hasCJKLanguage = true
enableCsrf = true

[[menu.main]]
    identifier = "archives"
    name = "归档"
    weight = 10
    
[[menu.main]]
    identifier = "posts"
    name = "时间"
    url = "posts"
    weight = 10
    parent = "archives"

[[menu.main]]
    identifier = "category"
    name = "分类"
    url = "category"
    weight = 10
    parent = "archives"

[[menu.main]]
    identifier = "tags"
    name = "标签"
    url = "tags"
    weight = 10
    parent = "archives"

[[menu.main]]
    identifier = "links"
    name = "友链"
    url = "links"
    weight = 20

[[menu.main]]
    identifier = "whisper"
    name = "碎语"
    url = "whisper"
    weight = 30

[[menu.main]]
    identifier = "now"
    name = "如今"
    url = "now"
    weight = 40

[[menu.main]]
    identifier = "about"
    name = "关于"
    url = "about"
    weight = 50

[[menu.main]]
    identifier = "travelling"
    name = "开往"
    url = "https://www.travellings.cn/go.html"
    weight = 60

[params]

    # 基本信息
    [params.basic]
        title = "Title"
        description = "Description"
        banner = "/img/banner.webp"
        startDate = "12/15/2023 12:00:00"
        announcement = true
        showMath = true
        darkMode = true

    # 作者信息
    [params.author]
        name = "Author"
        homepage = "https://example.com"
        description = "Description"
        avatar = "https://example.com/avatar.webp"
        
    # 社交链接，支持多种社交平台，你可以根据自己的需求添加或删除。但是推荐别太多，不然会显得很乱。
    [[params.social]]
        name = "Home"
        url = ""
        icon = "i-carbon-home"
        enable = false
    [[params.social]]
        name = "Email"
        url = "mailto:you@mail.com"
        icon = "i-carbon-email"
        enable = false
    [[params.social]]
        name = "RSS"
        url = "/index.xml"
        icon = "i-carbon-rss"
        enable = false
    [[params.social]]
        name = "Newsletter"
        url = "https://your.newsletter.link"
        icon = "i-mdi-email-newsletter"
        enable = false
    [[params.social]]
        name = "GitHub"
        url = "https://github.com/username"
        icon = "i-carbon-logo-github"
        enable = false
    [[params.social]]
        name = "GitLab"
        url = ""
        icon = "i-carbon-logo-gitlab"
        enable = false
    [[params.social]]
        name = "Gitee"
        url = "https://gitee.com/username"
        icon = "i-simple-gitee"
        enable = false
    [[params.social]]
        name = "Codeberg"
        url = "https://codeberg.org/username"
        icon = "i-simple-codeberg"
        enable = false
    [[params.social]]
        name = "YouTube"
        url = "https://www.youtube.com/@username"
        icon = "i-carbon-logo-youtube"
        enable = false
    [[params.social]]
        name = "Bilibili"
        url = "https://space.bilibili.com/userid"
        icon = "i-simple-bilibili"
        enable = false
    [[params.social]]
        name = "ORCID"
        url = "https://orcid.org/your-orcid"
        icon = "i-simple-orcid"
        enable = false
    [[params.social]]
        name = "Matrix"
        url = "https://matrix.to/#/#username:matrix.org"
        icon = "i-simple-matrix"
        enable = false
    [[params.social]]
        name = "Fediverse"
        url = "https://your.instance/@username"
        icon = "i-carbon-logo-mastodon"
        enable = false

    # 联邦宇宙的说说参数
    [params.whisper]
        instance = "https://your.instance"
        user_id = "your_user_id"
        bot_token = "your_bot_token"

    [params.term]
        showTableOfContents = false

    # ICP 备案、公安联网备案和萌 ICP 备案 =w=
    [params.icp]
        enable = true
        number = "Your ICP Number"

    [params.mps]
        enable = true
        number = "Your MPS Number"
        code = "the-num-code" # 很抱歉需要大家填写两次，但是根据公安部的规定，链接跳转的时候需要直接带上 query 参数，所以只能这样了。

    [params.moe]
        enable = true
        number = "Your MOEICP Number"
        code = "the-num-code"

    [params.twikoo]
        enable = false
        envId = "Your EnvId"

    [params.wowbook]
        enable = true

    # 注意这是 Algolia Docsearch，不是普通的 Algolia 搜索
    [params.algolia]
        enable = false
        appid = "Your AppId"
        apiKey = "Your API Key"
        indexname = "Your Index Name"
        container = "#docsearch"
        debug = false

[taxonomies]
    category = "category"
    tag = "tags"
    series = "series"

[Permalinks]
    posts = "/:slug/"

[sitemap]
    changefreq = "weekly"
    filename = "sitemap.xml"
    priority = 0.5

[outputs]
    home = ["HTML", "RSS"]

[markup]
    [markup.asciidocExt]
        preserveTOC = true
    [markup.highlight]
        guessSyntax = true
        lineNos = false
        lineNumbersInTable = true
        codeFences = false
        noClasses = false
        style = "monokai"
        tabWidth = 4
    [markup.tableOfContents]
        endLevel = 5
        ordered = true
        startLevel = 2
    [markup.goldmark]
        # 数学公式定界，千万别改！否则后果自负！
        [markup.goldmark.renderer]
            unsafe = true
        [markup.goldmark.extensions.passthrough]
            enable = true
            delimiters.block = [["$$", "$$"]]
            delimiters.inline = [["$", "$"]]